In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import tensorflow as tf

# import sqlalchemy
# from sqlalchemy.ext.automap import automap_base
# from sqlalchemy.orm import Session
# from sqlalchemy import create_engine, func
import sqlite3
import psycopg2

In [2]:
conn = psycopg2.connect("dbname=ipo-database user=postgres password=0nlineSQL")

In [3]:
# Check if we connected to our DB
cur = conn.cursor()
cur.execute('SELECT version()')

db_version = cur.fetchone()
print(db_version)

('PostgreSQL 11.10, compiled by Visual C++ build 1914, 64-bit',)

In [4]:
# Execute the "SELECT *" query for our first table and store the data as a variable
company_overview_df = pd.read_sql_query("SELECT * from company_overview;", conn)
company_overview_df.head()

,symbol,asset_type,company_name,exchange,currency,country,sector,industry,address
0,MRM,Common Stock,MEDIROM Healthcare Technologies Inc,NASDAQ,USD,USA,Consumer Cyclical,Personal Services,"Tradepia Odaiba, Tokyo, Japan, 135-0091"
1,VTAQ,Common Stock,Ventoux CCM Acquisition Corp,NASDAQ,USD,USA,Financial Services,Shell Companies,"1 East Putnam Avenue, Greenwich, CT, United St..."
2,IKT,Common Stock,"Inhibikase Therapeutics, Inc",NASDAQ,USD,USA,Healthcare,Biotechnology,"3350 Riverwood Parkway, Atlanta, GA, United St..."
3,GBS,Common Stock,GBS Inc,NASDAQ,USD,USA,Healthcare,Medical Devices,"708 3rd Avenue, New York, NY, United States, 1..."
4,HCAR,Common Stock,Healthcare Services Acquisition Corporation,NASDAQ,USD,USA,Financial Services,Shell Companies,"7809 Woodmont Avenue, Bethesda, MD, United Sta..."

In [5]:
# Execute the "SELECT *" query for our second table and store the data as a variable
three_month_df = pd.read_sql_query("SELECT * from three_month_return;", conn)
three_month_df.head()

,symbol,ipo_date,company_name,ipo_price,current_price,percentage_return,three_mth_date,three_mth_ipo,price_change,three_mth_return,price_gain_loss
0,SVOK,2020-12-18,Seven Oaks Acquisition,10.0,9.91,-0.009,2021-03-18,10.0450,0.0450,0.00450,Gain
1,GFX,2020-12-18,Golden Falcon Acquisition,10.0,9.83,-0.017,2021-03-18,9.7516,-0.2484,-0.02484,Loss
2,MASS,2020-12-18,908 Devices,20.0,53.80,1.690,2021-03-18,49.3800,29.3800,1.46900,Gain
3,DUNE,2020-12-18,Dune Acquisition,10.0,9.74,-0.026,2021-03-18,9.7600,-0.2400,-0.02400,Loss
4,MTAC,2020-12-18,MedTech Acquisition,10.0,9.94,-0.006,2021-03-18,9.8800,-0.1200,-0.01200,Loss

In [76]:
income_df = pd.read_sql_query("SELECT * from filtered_income_statement;", conn)
income_df

,symbol,fiscaldate_end,reported_currency,gross_profit,total_revenue,costof_revenue,costof_goodservices_sold,operating_income,selling_gen_admin,research_dev,...,depreciation,dpr_and_amort,income_beforetax,incometax_expense,interest_debt_expense,netincome_cont_operations,comprehensive_income_netoftax,ebit,ebitda,netincome
0,ABCM,2020-09-30,GBP,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.000000e+00,1050000.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00
1,ABNB,2020-12-31,USD,6.495170e+08,8.592640e+08,2.097470e+08,209747000.0,-3.085794e+09,1.343584e+09,2.062195e+09,...,0.0,0.0,-3.992502e+09,-104651000.0,0.0,-3.887851e+09,0.0,-3.895924e+09,0.0,-3.887851e+09
2,ABST,2020-09-30,USD,2.538015e+07,2.849556e+07,3.115407e+06,3115407.0,4.198883e+06,1.611957e+07,5.061693e+06,...,0.0,0.0,3.895944e+06,1294000.0,0.0,2.601944e+06,0.0,5.390617e+06,0.0,2.601944e+06
3,ACCD,2020-05-31,USD,2.249300e+07,4.444100e+07,2.194800e+07,21948000.0,-1.262500e+07,1.287700e+07,1.137000e+07,...,0.0,0.0,-1.392200e+07,38000.0,0.0,-1.396000e+07,0.0,8.960000e+05,0.0,-1.396000e+07
4,ACI,2020-06-20,USD,6.771500e+09,2.275160e+10,1.598010e+10,0.0,9.718000e+08,5.769400e+09,0.000000e+00,...,0.0,0.0,7.881000e+08,201900000.0,0.0,5.862000e+08,587900000.0,9.718000e+08,0.0,5.862000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,YQ,2020-12-31,CNY,3.132190e+08,4.867870e+08,1.735680e+08,173568000.0,-3.631550e+08,4.842350e+08,1.921390e+08,...,0.0,0.0,-3.650590e+08,0.0,0.0,-3.650590e+08,0.0,-3.649750e+08,0.0,-3.650590e+08
332,YSG,2020-12-31,CNY,1.301010e+09,1.961598e+09,6.605880e+08,660588000.0,-1.533852e+09,2.809252e+09,2.561000e+07,...,0.0,0.0,-1.532857e+09,-1653000.0,0.0,-1.531204e+09,0.0,-1.533852e+09,0.0,-1.530596e+09
333,ZCMD,2020-03-31,USD,2.810746e+06,4.231125e+06,0.000000e+00,0.0,0.000000e+00,1.668508e+06,0.000000e+00,...,0.0,0.0,0.000000e+00,261240.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00
334,ZGYH,2019-12-31,USD,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,1.100150e+06,0.0,0.000000e+00
335,ZNTL,2020-03-31,USD,0.000000e+00,0.000000e+00,0.000000e+00,0.0,-1.639900e+07,3.141000e+06,1.325800e+07,...,0.0,0.0,-1.623500e+07,0.0,0.0,-1.623500e+07,0.0,-1.636100e+07,0.0,-1.612600e+07

In [ ]:
# Net profit margin
income_df["gross_profit_margin"] = income_df[""]/income_df["total_revenue"]
income_df["gross_profit_margin"]

In [97]:
# Calculate Gross Profit Margin = gross_profit/total_revenue
income_df["gross_profit_margin"] = income_df["gross_profit"]/income_df["total_revenue"]
income_df["gross_profit_margin"]

0           NaN
1      0.755899
2      0.890670
3      0.506132
4      0.297627
         ...
331    0.643442
332    0.663240
333    0.664302
334         NaN
335         NaN
Name: gross_profit_margin, Length: 336, dtype: float64

In [100]:
income_df = income_df.dropna(subset=["gross_profit_margin"])
income_df

,symbol,fiscaldate_end,reported_currency,gross_profit,total_revenue,costof_revenue,costof_goodservices_sold,operating_income,selling_gen_admin,research_dev,...,dpr_and_amort,income_beforetax,incometax_expense,interest_debt_expense,netincome_cont_operations,comprehensive_income_netoftax,ebit,ebitda,netincome,gross_profit_margin
1,ABNB,2020-12-31,USD,6.495170e+08,8.592640e+08,2.097470e+08,2.097470e+08,-3.085794e+09,1.343584e+09,2.062195e+09,...,0.0,-3.992502e+09,-104651000.0,0.0,-3.887851e+09,0.0,-3.895924e+09,0.0,-3.887851e+09,0.755899
2,ABST,2020-09-30,USD,2.538015e+07,2.849556e+07,3.115407e+06,3.115407e+06,4.198883e+06,1.611957e+07,5.061693e+06,...,0.0,3.895944e+06,1294000.0,0.0,2.601944e+06,0.0,5.390617e+06,0.0,2.601944e+06,0.890670
3,ACCD,2020-05-31,USD,2.249300e+07,4.444100e+07,2.194800e+07,2.194800e+07,-1.262500e+07,1.287700e+07,1.137000e+07,...,0.0,-1.392200e+07,38000.0,0.0,-1.396000e+07,0.0,8.960000e+05,0.0,-1.396000e+07,0.506132
4,ACI,2020-06-20,USD,6.771500e+09,2.275160e+10,1.598010e+10,0.000000e+00,9.718000e+08,5.769400e+09,0.000000e+00,...,0.0,7.881000e+08,201900000.0,0.0,5.862000e+08,587900000.0,9.718000e+08,0.0,5.862000e+08,0.297627
7,AFYA,2019-06-30,BRL,9.621000e+07,1.784930e+08,8.228300e+07,8.228300e+07,3.720200e+07,5.958400e+07,0.000000e+00,...,0.0,2.305100e+07,1725000.0,0.0,2.132600e+07,0.0,2.828700e+07,0.0,1.631700e+07,0.539013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,YALA,2020-09-30,USD,8.217837e+06,3.382631e+07,2.560848e+07,2.560848e+07,-3.089731e+07,3.742498e+07,1.698495e+06,...,0.0,-3.087116e+07,109112.0,0.0,-3.098028e+07,0.0,-3.090126e+07,0.0,-3.098028e+07,0.242942
330,YJ,2019-03-31,CNY,6.545180e+08,3.385555e+09,2.731037e+09,2.731037e+09,1.680000e+05,6.543500e+08,5.000000e-02,...,0.0,2.038700e+07,2265000.0,0.0,1.686200e+07,0.0,5.430000e+06,0.0,1.474500e+07,0.193327
331,YQ,2020-12-31,CNY,3.132190e+08,4.867870e+08,1.735680e+08,1.735680e+08,-3.631550e+08,4.842350e+08,1.921390e+08,...,0.0,-3.650590e+08,0.0,0.0,-3.650590e+08,0.0,-3.649750e+08,0.0,-3.650590e+08,0.643442
332,YSG,2020-12-31,CNY,1.301010e+09,1.961598e+09,6.605880e+08,6.605880e+08,-1.533852e+09,2.809252e+09,2.561000e+07,...,0.0,-1.532857e+09,-1653000.0,0.0,-1.531204e+09,0.0,-1.533852e+09,0.0,-1.530596e+09,0.663240
333,ZCMD,2020-03-31,USD,2.810746e+06,4.231125e+06,0.000000e+00,0.000000e+00,0.000000e+00,1.668508e+06,0.000000e+00,...,0.0,0.000000e+00,261240.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.664302

In [94]:
balance_sheet_df = pd.read_sql_query("SELECT * from filtered_balance_sheet;", conn)
balance_sheet_df

,symbol,fiscaldate_end,reported_currency,total_assets,total_current_assets,cash_cashequivalent_carrvalue,cash_shortterm_investments,inventory,currentnet_receivables,total_noncurrent_assets,...,current_longterm_debt,longterm_debt_noncurrent,short_longterm_debt_total,other_current_liabilities,other_noncurrent_liabilities,total_shareholder_equity,treasury_stock,retained_earnings,common_stock,common_stockshares_outstanding
0,AACQ,2020-07-16,USD,1.385431e+06,1.385431e+06,1.385431e+06,1.385431e+06,0.0,0.0,0.000000e+00,...,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0
1,ABCM,2020-09-30,GBP,0.000000e+00,3.075000e+08,0.000000e+00,0.000000e+00,43400000.0,0.0,0.000000e+00,...,0.0,0.0,0.000000e+00,1.500000e+06,0.0,0.000000e+00,0.0,2.723000e+08,500000.0,0.0
2,ABNB,2020-12-31,USD,1.049150e+10,8.916386e+09,5.480557e+09,5.480557e+09,0.0,0.0,1.575113e+09,...,26755000.0,0.0,1.842317e+09,4.019636e+09,203470000.0,2.901783e+09,0.0,-6.005707e+09,60000.0,599197000.0
3,ABST,2020-09-30,USD,1.366821e+08,9.398931e+07,5.129583e+07,5.129583e+07,0.0,0.0,4.269279e+07,...,0.0,0.0,0.000000e+00,8.584784e+07,0.0,-4.048714e+07,0.0,-1.631903e+08,83042897.0,42668703.0
4,ACCD,2020-05-31,USD,1.204820e+08,9.675400e+07,7.768200e+07,7.768200e+07,0.0,0.0,2.372800e+07,...,0.0,0.0,7.252400e+07,3.945100e+07,0.0,-2.664970e+08,0.0,-3.348280e+08,2000.0,46653451.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,ZCMD,2020-03-31,USD,0.000000e+00,2.693504e+07,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,...,0.0,0.0,0.000000e+00,1.897302e+06,0.0,0.000000e+00,0.0,5.141224e+06,2492.0,0.0
447,ZGYH,2019-12-31,USD,2.183410e+05,2.689000e+03,2.689000e+03,2.689000e+03,0.0,0.0,2.156520e+05,...,175339.0,0.0,1.753390e+05,0.000000e+00,0.0,1.978800e+04,0.0,-5.212000e+03,144.0,8944500.0
448,ZI,2020-06-30,USD,1.919300e+09,3.727000e+08,2.591000e+08,2.591000e+08,0.0,93500000.0,1.397000e+09,...,0.0,743700000.0,7.437000e+08,1.887000e+08,5700000.0,3.876000e+08,0.0,-3.440000e+07,3900000.0,389253891.0
449,ZM,2019-04-30,USD,6.321370e+08,6.299930e+08,6.297930e+08,6.297930e+08,0.0,78888000.0,2.144000e+06,...,5693000.0,0.0,0.000000e+00,3.960000e+06,26850000.0,7.197280e+08,0.0,-2.293900e+07,271000.0,136000000.0
450,ZNTL,2020-03-31,USD,8.762900e+07,6.600900e+07,6.365000e+07,6.365000e+07,0.0,139000.0,1.926700e+07,...,0.0,0.0,0.000000e+00,0.000000e+00,1484000.0,-9.590300e+07,0.0,-9.911900e+07,3216000.0,34501524.0

### Calculate Debt Asset Ratio:

The formula for the debt to asset ratio is as follows: Debt/Asset = (Short-term Debt + Long-term Debt) / Total Assets. Where: Total Assets may include all current and non-current assets on the company's balance sheet, or may only include certain assets such as Property, Plant & Equipment (PP&E)

In [101]:
balance_sheet_df["debt_asset_ratio"] = balance_sheet_df["short_longterm_debt_total"]/balance_sheet_df["total_assets"]
balance_sheet_df

,symbol,fiscaldate_end,reported_currency,total_assets,total_current_assets,cash_cashequivalent_carrvalue,cash_shortterm_investments,inventory,currentnet_receivables,total_noncurrent_assets,...,longterm_debt_noncurrent,short_longterm_debt_total,other_current_liabilities,other_noncurrent_liabilities,total_shareholder_equity,treasury_stock,retained_earnings,common_stock,common_stockshares_outstanding,debt_asset_ratio
0,AACQ,2020-07-16,USD,1.385431e+06,1.385431e+06,1.385431e+06,1.385431e+06,0.0,0.0,0.000000e+00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.000000
1,ABCM,2020-09-30,GBP,0.000000e+00,3.075000e+08,0.000000e+00,0.000000e+00,43400000.0,0.0,0.000000e+00,...,0.0,0.000000e+00,1.500000e+06,0.0,0.000000e+00,0.0,2.723000e+08,500000.0,0.0,NaN
2,ABNB,2020-12-31,USD,1.049150e+10,8.916386e+09,5.480557e+09,5.480557e+09,0.0,0.0,1.575113e+09,...,0.0,1.842317e+09,4.019636e+09,203470000.0,2.901783e+09,0.0,-6.005707e+09,60000.0,599197000.0,0.175601
3,ABST,2020-09-30,USD,1.366821e+08,9.398931e+07,5.129583e+07,5.129583e+07,0.0,0.0,4.269279e+07,...,0.0,0.000000e+00,8.584784e+07,0.0,-4.048714e+07,0.0,-1.631903e+08,83042897.0,42668703.0,0.000000
4,ACCD,2020-05-31,USD,1.204820e+08,9.675400e+07,7.768200e+07,7.768200e+07,0.0,0.0,2.372800e+07,...,0.0,7.252400e+07,3.945100e+07,0.0,-2.664970e+08,0.0,-3.348280e+08,2000.0,46653451.0,0.601949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,ZCMD,2020-03-31,USD,0.000000e+00,2.693504e+07,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,...,0.0,0.000000e+00,1.897302e+06,0.0,0.000000e+00,0.0,5.141224e+06,2492.0,0.0,NaN
447,ZGYH,2019-12-31,USD,2.183410e+05,2.689000e+03,2.689000e+03,2.689000e+03,0.0,0.0,2.156520e+05,...,0.0,1.753390e+05,0.000000e+00,0.0,1.978800e+04,0.0,-5.212000e+03,144.0,8944500.0,0.803051
448,ZI,2020-06-30,USD,1.919300e+09,3.727000e+08,2.591000e+08,2.591000e+08,0.0,93500000.0,1.397000e+09,...,743700000.0,7.437000e+08,1.887000e+08,5700000.0,3.876000e+08,0.0,-3.440000e+07,3900000.0,389253891.0,0.387485
449,ZM,2019-04-30,USD,6.321370e+08,6.299930e+08,6.297930e+08,6.297930e+08,0.0,78888000.0,2.144000e+06,...,0.0,0.000000e+00,3.960000e+06,26850000.0,7.197280e+08,0.0,-2.293900e+07,271000.0,136000000.0,0.000000
450,ZNTL,2020-03-31,USD,8.762900e+07,6.600900e+07,6.365000e+07,6.365000e+07,0.0,139000.0,1.926700e+07,...,0.0,0.000000e+00,0.000000e+00,1484000.0,-9.590300e+07,0.0,-9.911900e+07,3216000.0,34501524.0,0.000000

In [103]:
balance_sheet_df = balance_sheet_df.dropna(subset=["debt_asset_ratio"])
balance_sheet_df

,symbol,fiscaldate_end,reported_currency,total_assets,total_current_assets,cash_cashequivalent_carrvalue,cash_shortterm_investments,inventory,currentnet_receivables,total_noncurrent_assets,...,longterm_debt_noncurrent,short_longterm_debt_total,other_current_liabilities,other_noncurrent_liabilities,total_shareholder_equity,treasury_stock,retained_earnings,common_stock,common_stockshares_outstanding,debt_asset_ratio
0,AACQ,2020-07-16,USD,1.385431e+06,1.385431e+06,1.385431e+06,1.385431e+06,0.0,0.0,0.000000e+00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.000000
2,ABNB,2020-12-31,USD,1.049150e+10,8.916386e+09,5.480557e+09,5.480557e+09,0.0,0.0,1.575113e+09,...,0.0,1.842317e+09,4.019636e+09,203470000.0,2.901783e+09,0.0,-6.005707e+09,60000.0,5.991970e+08,0.175601
3,ABST,2020-09-30,USD,1.366821e+08,9.398931e+07,5.129583e+07,5.129583e+07,0.0,0.0,4.269279e+07,...,0.0,0.000000e+00,8.584784e+07,0.0,-4.048714e+07,0.0,-1.631903e+08,83042897.0,4.266870e+07,0.000000
4,ACCD,2020-05-31,USD,1.204820e+08,9.675400e+07,7.768200e+07,7.768200e+07,0.0,0.0,2.372800e+07,...,0.0,7.252400e+07,3.945100e+07,0.0,-2.664970e+08,0.0,-3.348280e+08,2000.0,4.665345e+07,0.601949
5,ACEV,2020-06-30,USD,2.814960e+05,2.814960e+05,1.147000e+03,1.147000e+03,0.0,0.0,0.000000e+00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,YSG,2020-12-31,CNY,8.307738e+09,7.088528e+09,5.727029e+09,5.727029e+09,616808000.0,0.0,1.219210e+09,...,0.0,5.272100e+08,3.672800e+07,0.0,6.848510e+09,0.0,-4.220083e+09,173000.0,2.526454e+09,0.063460
447,ZGYH,2019-12-31,USD,2.183410e+05,2.689000e+03,2.689000e+03,2.689000e+03,0.0,0.0,2.156520e+05,...,0.0,1.753390e+05,0.000000e+00,0.0,1.978800e+04,0.0,-5.212000e+03,144.0,8.944500e+06,0.803051
448,ZI,2020-06-30,USD,1.919300e+09,3.727000e+08,2.591000e+08,2.591000e+08,0.0,93500000.0,1.397000e+09,...,743700000.0,7.437000e+08,1.887000e+08,5700000.0,3.876000e+08,0.0,-3.440000e+07,3900000.0,3.892539e+08,0.387485
449,ZM,2019-04-30,USD,6.321370e+08,6.299930e+08,6.297930e+08,6.297930e+08,0.0,78888000.0,2.144000e+06,...,0.0,0.000000e+00,3.960000e+06,26850000.0,7.197280e+08,0.0,-2.293900e+07,271000.0,1.360000e+08,0.000000
450,ZNTL,2020-03-31,USD,8.762900e+07,6.600900e+07,6.365000e+07,6.365000e+07,0.0,139000.0,1.926700e+07,...,0.0,0.000000e+00,0.000000e+00,1484000.0,-9.590300e+07,0.0,-9.911900e+07,3216000.0,3.450152e+07,0.000000

In [95]:
cash_flow_df = pd.read_sql_query("SELECT * from filtered_cash_flow;", conn)
cash_flow_df

,symbol,fiscaldate_end,reported_currency,operating_cashflow,payments_foroperating_activities,proceeds_fromoperating_activities,changein_operating_liabilities,changein_operating_assets,dpr_depletion_amort,capital_expenditures,...,div_payout_commonstock,div_payout_preferredstock,proceeds_fromissuance_commonstock,proceeds_fromissuance_longterm_debtcapital_secnet,proceeds_fromissuance_preferredstock,proceeds_fromrepurchase_equity,proceeds_fromsale_treasurystock,changein_cash_cashequivalents,changein_exchangerate,netincome
0,ABCM,2020-09-30,GBP,1.695000e+07,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00
1,ABNB,2020-12-31,USD,-1.391100e+08,0.0,0.0,0.0,0.0,32438000.0,7882000.0,...,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,-3.887851e+09
2,ABST,2020-09-30,USD,1.470726e+07,0.0,0.0,0.0,0.0,1356024.0,945871.0,...,-2580376.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,2.601944e+06
3,ACCD,2020-05-31,USD,-8.317000e+06,0.0,0.0,0.0,0.0,1928000.0,538000.0,...,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,-1.396000e+07
4,ACI,2020-06-20,USD,2.091900e+09,63500000.0,0.0,733100000.0,-63100000.0,0.0,0.0,...,0.0,0.0,0.0,2.000000e+09,0.0,0.0,0.0,1.585600e+09,0.0,5.862000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,YSG,2020-12-31,CNY,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,-1.530596e+09
331,ZCMD,2020-03-31,USD,-1.186251e+06,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00
332,ZGYH,2019-12-31,USD,-8.600000e+01,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,-1.300000e+02
333,ZI,2020-06-30,USD,2.530000e+07,0.0,0.0,0.0,0.0,-24200000.0,0.0,...,0.0,0.0,0.0,0.000000e+00,0.0,-320500000.0,0.0,0.000000e+00,0.0,-1.960000e+07
334,ZNTL,2020-03-31,USD,-1.687100e+07,0.0,0.0,0.0,0.0,38000.0,31000.0,...,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,-1.612600e+07

# Preprocess

In [61]:
IPO_df = pd.merge(three_month_df, company_overview_df, left_on = 'symbol', right_on= 'symbol', how='left')

In [62]:
IPO_df

,symbol,ipo_date,company_name_x,ipo_price,current_price,percentage_return,three_mth_date,three_mth_ipo,price_change,three_mth_return,price_gain_loss,asset_type,company_name_y,exchange,currency,country,sector,industry,address
0,SVOK,2020-12-18,Seven Oaks Acquisition,10.0,9.91,-0.0090,2021-03-18,10.0450,0.0450,0.004500,Gain,Common Stock,Seven Oaks Acquisition Corp,NASDAQ,USD,USA,Financial Services,Shell Companies,"445 Park Avenue, New York, NY, United States, ..."
1,GFX,2020-12-18,Golden Falcon Acquisition,10.0,9.83,-0.0170,2021-03-18,9.7516,-0.2484,-0.024840,Loss,Common Stock,Golden Falcon Acquisition Corp,NYSE,USD,USA,Financial Services,Shell Companies,"850 Library Avenue, Newark, DE, United States,..."
2,MASS,2020-12-18,908 Devices,20.0,53.80,1.6900,2021-03-18,49.3800,29.3800,1.469000,Gain,Common Stock,908 Devices Inc,NASDAQ,USD,USA,Healthcare,Medical Devices,"645 Summer Street, Boston, MA, United States, ..."
3,DUNE,2020-12-18,Dune Acquisition,10.0,9.74,-0.0260,2021-03-18,9.7600,-0.2400,-0.024000,Loss,Common Stock,Dune Acquisition Corporation,NASDAQ,USD,USA,Financial Services,Shell Companies,"700 South Rosemary Avenue, West Palm Beach, FL..."
4,MTAC,2020-12-18,MedTech Acquisition,10.0,9.94,-0.0060,2021-03-18,9.8800,-0.1200,-0.012000,Loss,Common Stock,MedTech Acquisition Corporation,NASDAQ,USD,USA,Financial Services,Shell Companies,"600 Fifth Avenue, New York, NY, United States,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,RBKB,2019-01-17,Rhinebeck Bancorp,10.0,10.49,0.0490,2019-04-17,11.6600,1.6600,0.166000,Gain,Common Stock,"Rhinebeck Bancorp, Inc",NASDAQ,USD,USA,Financial Services,Banks-Regional,"2 Jefferson Plaza, Poughkeepsie, NY, United St..."
479,BCOW,2019-01-09,1895 Bancorp of Wisconsin,10.0,14.94,0.4940,2019-04-09,9.6700,-0.3300,-0.033000,Loss,Common Stock,"1895 Bancorp of Wisconsin, Inc",NASDAQ,USD,USA,Financial Services,Banks-Regional,"7001 West Edgerton Avenue, Greenfield, WI, Uni..."
480,MDJH,2019-01-08,MDJM Ltd.,5.0,4.25,-0.1500,2019-04-08,3.4730,-1.5270,-0.305400,Loss,Common Stock,MDJM Ltd,NASDAQ,USD,USA,Real Estate,Real Estate Services,"Saidun Center, Tianjin, China"
481,MTC,2019-01-08,"MMTec, Inc.",4.0,2.83,-0.2925,2019-04-08,4.3301,0.3301,0.082525,Gain,Common Stock,"Mmtec, Inc",NASDAQ,USD,USA,Technology,Software-Application,"Air China Century Building, Beijing, China, 10..."
482,SXTC,2019-01-04,China SXT Pharmaceuticals,4.0,2.03,-0.4925,2019-04-04,6.4200,2.4200,0.605000,Gain,Common Stock,"China SXT Pharmaceuticals, Inc",NASDAQ,USD,USA,Healthcare,Drug Manufacturers-Specialty & Generic,"No.178 North Taidong Road, Taizhou, China, 225300"

In [63]:
IPO_df = IPO_df.drop(["symbol","company_name_x", "company_name_y","address","asset_type", "currency", "country","ipo_price", "current_price", "percentage_return", "three_mth_ipo", "price_change","three_mth_return",],1)

In [64]:
IPO_df.nunique()

ipo_date           184
three_mth_date     183
price_gain_loss      2
exchange             6
sector              13
industry            68
dtype: int64

In [65]:
# Temporarily remove dates to test - need to convert datetime still
IPO_df = IPO_df.drop(["ipo_date","three_mth_date"],1)
IPO_df.head()

  price_gain_loss exchange              sector         industry
0            Gain   NASDAQ  Financial Services  Shell Companies
1            Loss     NYSE  Financial Services  Shell Companies
2            Gain   NASDAQ          Healthcare  Medical Devices
3            Loss   NASDAQ  Financial Services  Shell Companies
4            Loss   NASDAQ  Financial Services  Shell Companies

In [66]:
IPO_df.head()

  price_gain_loss exchange              sector         industry
0            Gain   NASDAQ  Financial Services  Shell Companies
1            Loss     NYSE  Financial Services  Shell Companies
2            Gain   NASDAQ          Healthcare  Medical Devices
3            Loss   NASDAQ  Financial Services  Shell Companies
4            Loss   NASDAQ  Financial Services  Shell Companies

In [35]:
# IPO_df = IPO_df[IPO_df["sector"]=="Healthcare"]
# IPO_df

,ipo_price,current_price,percentage_return,three_mth_ipo,price_change,three_mth_return,price_gain_loss,exchange,sector,industry
2,20.00,53.80,1.6900,49.38,29.38,1.469000,Gain,NASDAQ,Healthcare,Medical Devices
9,10.00,6.16,-0.3840,6.16,-3.84,-0.384000,Loss,NASDAQ,Healthcare,Biotechnology
13,5.50,9.89,0.7982,9.88,4.38,0.796364,Gain,NASDAQ,Healthcare,Biotechnology
14,18.00,66.96,2.7200,66.53,48.53,2.696111,Gain,NASDAQ,Healthcare,Biotechnology
21,20.00,36.29,0.8145,36.00,16.00,0.800000,Gain,NASDAQ,Healthcare,Biotechnology
...,...,...,...,...,...,...,...,...,...,...
469,5.13,2.06,-0.5980,3.98,-1.15,-0.224172,Loss,NASDAQ,Healthcare,Medical Care Facilities
470,14.00,19.07,0.3621,10.41,-3.59,-0.256429,Loss,NASDAQ,Healthcare,Biotechnology
472,16.00,9.38,-0.4138,18.17,2.17,0.135625,Gain,NASDAQ,Healthcare,Biotechnology
474,19.00,21.02,0.1063,18.74,-0.26,-0.013684,Loss,NASDAQ,Healthcare,Biotechnology
482,4.00,2.03,-0.4925,6.42,2.42,0.605000,Gain,NASDAQ,Healthcare,Drug Manufacturers-Specialty & Generic

# Encoding

In [67]:
# Binary encode
IPO_df_encoded = pd.get_dummies(IPO_df, columns=["exchange","sector","industry","price_gain_loss"])
IPO_df_encoded.head()

,exchange_CSE,exchange_NASDAQ,exchange_NYSE,exchange_NYSE MKT,exchange_OTCMKTS,exchange_PINK,sector_Basic Materials,sector_Communication Services,sector_Consumer Cyclical,sector_Consumer Defensive,...,industry_Specialty Industrial Machinery,industry_Specialty Retail,industry_Staffing & Employment Services,industry_Telecom Services,industry_Thermal Coal,industry_Trucking,industry_Utilities-Regulated Gas,industry_Waste Management,price_gain_loss_Gain,price_gain_loss_Loss
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

# Target Feature

In [68]:
y = IPO_df_encoded.price_gain_loss_Gain
X = IPO_df_encoded.drop(columns=["price_gain_loss_Gain","price_gain_loss_Loss"])

In [69]:
y

0      1
1      0
2      1
3      0
4      0
      ..
478    1
479    0
480    0
481    1
482    1
Name: price_gain_loss_Gain, Length: 483, dtype: uint8

In [70]:
X

,exchange_CSE,exchange_NASDAQ,exchange_NYSE,exchange_NYSE MKT,exchange_OTCMKTS,exchange_PINK,sector_Basic Materials,sector_Communication Services,sector_Consumer Cyclical,sector_Consumer Defensive,...,industry_Software-Infrastructure,industry_Solar,industry_Specialty Industrial Machinery,industry_Specialty Retail,industry_Staffing & Employment Services,industry_Telecom Services,industry_Thermal Coal,industry_Trucking,industry_Utilities-Regulated Gas,industry_Waste Management
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
479,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
480,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
481,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
482,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
import numpy as np

X.describe()

,ipo_price,current_price,percentage_return,three_mth_ipo,price_change,exchange_CSE,exchange_NASDAQ,exchange_NYSE,exchange_NYSE MKT,exchange_OTCMKTS,...,industry_Specialty Industrial Machinery,industry_Specialty Retail,industry_Staffing & Employment Services,industry_Telecom Services,industry_Thermal Coal,industry_Trucking,industry_Utilities-Regulated Gas,industry_Waste Management,price_gain_loss_Gain,price_gain_loss_Loss
count,483.000000,483.000000,483.000000,483.000000,483.000000,483.000000,483.000000,483.000000,483.000000,483.000000,...,483.000000,483.000000,483.000000,483.000000,483.000000,483.000000,483.000000,483.000000,483.000000,483.000000
mean,14.290911,25.623644,0.641498,19.761020,5.470109,0.002070,0.631470,0.281573,0.012422,0.002070,...,0.002070,0.006211,0.002070,0.004141,0.002070,0.002070,0.002070,0.004141,0.608696,0.391304
std,9.671077,32.910112,1.393422,24.259549,17.086755,0.045502,0.482906,0.450233,0.110876,0.045502,...,0.045502,0.078647,0.045502,0.064282,0.045502,0.045502,0.045502,0.064282,0.488548,0.488548
min,4.000000,1.130000,-0.885400,0.345200,-18.980000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,10.000000,-0.005000,9.910000,-0.238000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10.000000,12.600000,0.098000,11.020000,0.340000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,17.000000,28.550000,0.810600,22.915000,5.155000,0.000000,1.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,120.000000,326.260000,12.360000,329.970000,209.970000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# Split Training and Testing sets

In [81]:
# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Logistic Regression
our basic logistic regression parameters, which include:

- The solver parameter is set to 'lbfgs', which is an algorithm for learning and optimization. The particular solver isn't very important in this example, but note that a number of optimizers exist.
- The max_iter parameter will be set to 200 iterations, which will give the model sufficient opportunity to converge on effective weights

In [92]:
from sklearn.linear_model import LogisticRegression

# Define the logistic regression model
log_classifier = LogisticRegression(solver="lbfgs",max_iter=200)

# Train the model
log_classifier.fit(X_train,y_train)

# Evaluate the model
y_pred = log_classifier.predict(X_test)
print(f" Logistic regression model accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Logistic regression model accuracy: 0.554

# Random Forest

In [82]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random forest predictive accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Random forest predictive accuracy: 0.570

# SVM

In [84]:
from sklearn.svm import SVC

# Create the SVM model
svm = SVC(kernel='linear')

# Train the model
svm.fit(X_train, y_train)

# Evaluate the model
y_pred = svm.predict(X_test_scaled)
print(f" SVM model accuracy: {accuracy_score(y_test,y_pred):.3f}")

 SVM model accuracy: 0.438

# Deep Learning

In [85]:
len(X_train_scaled[0])

85

In [86]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  number_input_features*2
hidden_nodes_layer2 = number_input_features

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [87]:
# Train the model 
fit_model = nn.fit(X_train_scaled, y_train, epochs=100) 
# Evaluate the model using the test data 
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
12/12 [==============================] - 2s 3ms/step - loss: 0.6961 - accuracy: 0.5451
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 0.6061 - accuracy: 0.6837
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5787 - accuracy: 0.6982
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5418 - accuracy: 0.7127
Epoch 5/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5490 - accuracy: 0.7122
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5469 - accuracy: 0.7152
Epoch 7/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5614 - accuracy: 0.6916
Epoch 8/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5389 - accuracy: 0.7134
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5147 - accuracy: 0.7191
Epoch 10/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5306 - accuracy: 0.7011
Epoch 11/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5341 - accuracy: 0.6993
Epoch 12/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5144 - accuracy: 0.7379
Epoch 13/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5415 - accuracy: 0.7008
Epoch 14/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5316 - accuracy: 0.7117
Epoch 15/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5406 - accuracy: 0.6808
Epoch 16/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5267 - accuracy: 0.7037
Epoch 17/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5217 - accuracy: 0.7092
Epoch 18/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5240 - accuracy: 0.7130
Epoch 19/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5402 - accuracy: 0.7032
Epoch 20/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5598 - accuracy: 0.6546
Epoch 21/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5346 - accuracy: 0.6910
Epoch 22/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5473 - accuracy: 0.7317
Epoch 23/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5262 - accuracy: 0.7174
Epoch 24/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5380 - accuracy: 0.7259
Epoch 25/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5182 - accuracy: 0.7116
Epoch 26/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5341 - accuracy: 0.6923
Epoch 27/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5252 - accuracy: 0.7078
Epoch 28/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5413 - accuracy: 0.6797
Epoch 29/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5493 - accuracy: 0.6870
Epoch 30/100
12/12 [==============================] - 0s 2ms/step - loss: 0.4902 - accuracy: 0.7512
Epoch 31/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5101 - accuracy: 0.7339
Epoch 32/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5249 - accuracy: 0.7206
Epoch 33/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5121 - accuracy: 0.7224
Epoch 34/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4924 - accuracy: 0.7503
Epoch 35/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5520 - accuracy: 0.6908
Epoch 36/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5305 - accuracy: 0.7039
Epoch 37/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5420 - accuracy: 0.6821
Epoch 38/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5283 - accuracy: 0.7146
Epoch 39/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5114 - accuracy: 0.7067
Epoch 40/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5173 - accuracy: 0.7211
Epoch 41/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5448 - accuracy: 0.6909
Epoch 42/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5084 - accuracy: 0.7156
Epoch 43/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5175 - accuracy: 0.7098
Epoch 44/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5141 - accuracy: 0.7073
Epoch 45/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5076 - accuracy: 0.7184
Epoch 46/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5224 - accuracy: 0.7066
Epoch 47/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5285 - accuracy: 0.7116
Epoch 48/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5185 - accuracy: 0.7233
Epoch 49/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5666 - accuracy: 0.6551
Epoch 50/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5258 - accuracy: 0.7254
Epoch 51/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5173 - accuracy: 0.7252
Epoch 52/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5206 - accuracy: 0.7127
Epoch 53/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5003 - accuracy: 0.7241
Epoch 54/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5379 - accuracy: 0.6996
Epoch 55/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5417 - accuracy: 0.6937
Epoch 56/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5164 - accuracy: 0.7126
Epoch 57/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5301 - accuracy: 0.7098
Epoch 58/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5231 - accuracy: 0.7152
Epoch 59/100
12/12 [==============================] - 0s 997us/step - loss: 0.5220 - accuracy: 0.7133
Epoch 60/100
12/12 [==============================] - 0s 997us/step - loss: 0.5378 - accuracy: 0.6983
Epoch 61/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5337 - accuracy: 0.7190
Epoch 62/100
12/12 [==============================] - 0s 997us/step - loss: 0.5335 - accuracy: 0.7085
Epoch 63/100
12/12 [==============================] - 0s 997us/step - loss: 0.5129 - accuracy: 0.7047
Epoch 64/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5162 - accuracy: 0.7000
Epoch 65/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5269 - accuracy: 0.6906
Epoch 66/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5499 - accuracy: 0.6801
Epoch 67/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5123 - accuracy: 0.7099
Epoch 68/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5131 - accuracy: 0.7245
Epoch 69/100
12/12 [==============================] - 0s 907us/step - loss: 0.5288 - accuracy: 0.6856
Epoch 70/100
12/12 [==============================] - 0s 997us/step - loss: 0.5157 - accuracy: 0.7105
Epoch 71/100
12/12 [==============================] - 0s 997us/step - loss: 0.5068 - accuracy: 0.7092
Epoch 72/100
12/12 [==============================] - 0s 997us/step - loss: 0.5609 - accuracy: 0.6680
Epoch 73/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5305 - accuracy: 0.6991
Epoch 74/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5112 - accuracy: 0.7365
Epoch 75/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5422 - accuracy: 0.6817
Epoch 76/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5153 - accuracy: 0.7055
Epoch 77/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5205 - accuracy: 0.7143
Epoch 78/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5279 - accuracy: 0.7033
Epoch 79/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4970 - accuracy: 0.7490
Epoch 80/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5148 - accuracy: 0.7183
Epoch 81/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5223 - accuracy: 0.7132
Epoch 82/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5137 - accuracy: 0.7197
Epoch 83/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5178 - accuracy: 0.7166
Epoch 84/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5540 - accuracy: 0.6823
Epoch 85/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5420 - accuracy: 0.7109
Epoch 86/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5022 - accuracy: 0.7094
Epoch 87/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4981 - accuracy: 0.7408
Epoch 88/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5139 - accuracy: 0.7067
Epoch 89/100
12/12 [==============================] - 0s 997us/step - loss: 0.5296 - accuracy: 0.6949
Epoch 90/100
12/12 [==============================] - 0s 997us/step - loss: 0.5161 - accuracy: 0.7223
Epoch 91/100
12/12 [==============================] - 0s 997us/step - loss: 0.5048 - accuracy: 0.7303
Epoch 92/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5303 - accuracy: 0.6945
Epoch 93/100
12/12 [==============================] - 0s 907us/step - loss: 0.5309 - accuracy: 0.6823
Epoch 94/100
12/12 [==============================] - 0s 725us/step - loss: 0.5166 - accuracy: 0.7026
Epoch 95/100
12/12 [==============================] - 0s 3ms/step - loss: 0.5231 - accuracy: 0.7217
Epoch 96/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5313 - accuracy: 0.6994
Epoch 97/100
12/12 [==============================] - 0s 1ms/step - loss: 0.4998 - accuracy: 0.7325
Epoch 98/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5230 - accuracy: 0.6960
Epoch 99/100
12/12 [==============================] - 0s 1ms/step - loss: 0.5176 - accuracy: 0.7023
Epoch 100/100
12/12 [==============================] - 0s 997us/step - loss: 0.5059 - accuracy: 0.7186
4/4 - 0s - loss: 1.1976 - accuracy: 0.5950
Loss: 1.1976313591003418, Accuracy: 0.5950413346290588