In [3]:
import pandas as pd

# First Day

In [5]:
first_day_df = pd.read_csv('../first_day_results.csv')
first_day_df

,Index,debt_asset_ratio,debt_equity_ratio,current_ratio,OCF_ratio,gross_profit_margin,net_profit_margin,cashflow_frominvestment,EBIT_margin,sector_Basic Materials,...,industry_Staffing & Employment Services,industry_Telecom Services,industry_Travel Services,industry_Utilities-Regulated Gas,industry_Utilities-Regulated Water,industry_Utilities-Renewable,industry_Waste Management,actual_first_day_gain_loss,predicted_range,predicted_first_day_gain_loss
0,516,0.791023,-0.431128,1.669573,-0.056427,0.195109,-0.404897,-3778000.0,-0.079211,0,...,0,0,0,0,0,0,0,1,0.999595,1
1,588,2.834215,-2.639492,1.821186,0.354131,0.999992,0.258264,-565045.0,0.326479,0,...,0,0,0,0,0,0,0,1,0.746272,1
2,841,0.000000,0.000000,0.000000,-2.237563,0.000000,-9.541401,-4358000.0,-4.306794,0,...,0,0,0,0,0,0,0,0,0.253892,0
3,1142,0.000000,0.000000,6.355345,0.000000,1.000027,-0.292881,4323000.0,-0.256404,0,...,0,0,0,0,0,0,0,0,0.655895,1
4,1777,0.000000,0.000000,0.000000,0.000000,0.000000,0.177614,0.0,0.000000,0,...,0,0,0,0,0,0,0,0,0.038971,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,1244,0.000000,0.000000,1.638391,-0.145572,0.658848,-0.349033,-2734000.0,-0.318951,0,...,0,0,0,0,0,0,0,0,0.837803,1
68,644,0.000000,0.000000,1.596467,0.362813,0.772729,0.128499,-58746000.0,0.140411,0,...,0,0,0,0,0,0,0,1,0.404624,0
69,1005,0.000000,0.000000,0.000000,0.572817,0.000000,0.000000,0.0,0.000000,0,...,0,0,0,0,0,0,0,1,0.000015,0
70,2200,0.000000,0.000000,0.000000,1.122255,0.000000,-0.008407,0.0,0.000000,0,...,0,0,0,0,0,0,0,1,0.758314,1
71,1430,0.000000,0.000000,0.000000,0.228440,0.000000,0.000000,0.0,0.000000,0,...,0,0,0,0,0,0,0,1,0.999856,1

In [6]:
def undummify(df, prefix_sep="_"):
    cols2collapse = {
        item.split(prefix_sep)[0]: (prefix_sep in item) for item in df.columns
    }
    series_list = []
    for col, needs_to_collapse in cols2collapse.items():
        if needs_to_collapse:
            undummified = (
                df.filter(like=col)
                .idxmax(axis=1)
                .apply(lambda x: x.split(prefix_sep, maxsplit=1)[1])
                .rename(col)
            )
            series_list.append(undummified)
        else:
            series_list.append(df[col])
    undummified_df = pd.concat(series_list, axis=1)
    return undummified_df

In [7]:
undummied_df = undummify(first_day_df)

In [8]:
undummied_df

,Index,debt,current,OCF,gross,net,cashflow,EBIT,sector,industry,actual,predicted
0,516,asset_ratio,ratio,ratio,profit_margin,Internet Content & Information,frominvestment,margin,Industrials,Electrical Equipment & Parts,first_day_gain_loss,first_day_gain_loss
1,588,asset_ratio,ratio,ratio,profit_margin,profit_margin,frominvestment,margin,Financial Services,Insurance-Diversified,first_day_gain_loss,first_day_gain_loss
2,841,asset_ratio,ratio,ratio,profit_margin,Internet Content & Information,frominvestment,margin,Healthcare,Biotechnology,first_day_gain_loss,range
3,1142,asset_ratio,ratio,ratio,profit_margin,Internet Content & Information,frominvestment,margin,Other,Other,first_day_gain_loss,first_day_gain_loss
4,1777,asset_ratio,ratio,ratio,profit_margin,profit_margin,frominvestment,margin,Other,Other,first_day_gain_loss,range
...,...,...,...,...,...,...,...,...,...,...,...,...
67,1244,asset_ratio,ratio,ratio,profit_margin,Internet Content & Information,frominvestment,margin,Other,Other,first_day_gain_loss,first_day_gain_loss
68,644,asset_ratio,ratio,ratio,profit_margin,profit_margin,frominvestment,margin,Energy,Oil & Gas Equipment & Services,first_day_gain_loss,range
69,1005,asset_ratio,ratio,ratio,profit_margin,profit_margin,frominvestment,margin,Other,Other,first_day_gain_loss,range
70,2200,asset_ratio,ratio,ratio,profit_margin,Internet Content & Information,frominvestment,margin,Other,Other,first_day_gain_loss,first_day_gain_loss
71,1430,asset_ratio,ratio,ratio,profit_margin,profit_margin,frominvestment,margin,Other,Other,first_day_gain_loss,first_day_gain_loss

In [19]:
new_first_day_df = first_day_df[['debt_asset_ratio','debt_equity_ratio','current_ratio','OCF_ratio','gross_profit_margin','net_profit_margin','cashflow_frominvestment','EBIT_margin','actual_first_day_gain_loss','predicted_range','predicted_first_day_gain_loss']]
new_first_day_df

,debt_asset_ratio,debt_equity_ratio,current_ratio,OCF_ratio,gross_profit_margin,net_profit_margin,cashflow_frominvestment,EBIT_margin,actual_first_day_gain_loss,predicted_range,predicted_first_day_gain_loss
0,0.791023,-0.431128,1.669573,-0.056427,0.195109,-0.404897,-3778000.0,-0.079211,1,0.999595,1
1,2.834215,-2.639492,1.821186,0.354131,0.999992,0.258264,-565045.0,0.326479,1,0.746272,1
2,0.000000,0.000000,0.000000,-2.237563,0.000000,-9.541401,-4358000.0,-4.306794,0,0.253892,0
3,0.000000,0.000000,6.355345,0.000000,1.000027,-0.292881,4323000.0,-0.256404,0,0.655895,1
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.177614,0.0,0.000000,0,0.038971,0
...,...,...,...,...,...,...,...,...,...,...,...
67,0.000000,0.000000,1.638391,-0.145572,0.658848,-0.349033,-2734000.0,-0.318951,0,0.837803,1
68,0.000000,0.000000,1.596467,0.362813,0.772729,0.128499,-58746000.0,0.140411,1,0.404624,0
69,0.000000,0.000000,0.000000,0.572817,0.000000,0.000000,0.0,0.000000,1,0.000015,0
70,0.000000,0.000000,0.000000,1.122255,0.000000,-0.008407,0.0,0.000000,1,0.758314,1
71,0.000000,0.000000,0.000000,0.228440,0.000000,0.000000,0.0,0.000000,1,0.999856,1

In [20]:
new_first_day_df['sector'] = undummied_df['sector']
new_first_day_df

C:\Users\death\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,debt_asset_ratio,debt_equity_ratio,current_ratio,OCF_ratio,gross_profit_margin,net_profit_margin,cashflow_frominvestment,EBIT_margin,actual_first_day_gain_loss,predicted_range,predicted_first_day_gain_loss,sector
0,0.791023,-0.431128,1.669573,-0.056427,0.195109,-0.404897,-3778000.0,-0.079211,1,0.999595,1,Industrials
1,2.834215,-2.639492,1.821186,0.354131,0.999992,0.258264,-565045.0,0.326479,1,0.746272,1,Financial Services
2,0.000000,0.000000,0.000000,-2.237563,0.000000,-9.541401,-4358000.0,-4.306794,0,0.253892,0,Healthcare
3,0.000000,0.000000,6.355345,0.000000,1.000027,-0.292881,4323000.0,-0.256404,0,0.655895,1,Other
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.177614,0.0,0.000000,0,0.038971,0,Other
...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.000000,0.000000,1.638391,-0.145572,0.658848,-0.349033,-2734000.0,-0.318951,0,0.837803,1,Other
68,0.000000,0.000000,1.596467,0.362813,0.772729,0.128499,-58746000.0,0.140411,1,0.404624,0,Energy
69,0.000000,0.000000,0.000000,0.572817,0.000000,0.000000,0.0,0.000000,1,0.000015,0,Other
70,0.000000,0.000000,0.000000,1.122255,0.000000,-0.008407,0.0,0.000000,1,0.758314,1,Other
71,0.000000,0.000000,0.000000,0.228440,0.000000,0.000000,0.0,0.000000,1,0.999856,1,Other

In [21]:
new_first_day_df['industry'] = undummied_df['industry']
new_first_day_df

C:\Users\death\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,debt_asset_ratio,debt_equity_ratio,current_ratio,OCF_ratio,gross_profit_margin,net_profit_margin,cashflow_frominvestment,EBIT_margin,actual_first_day_gain_loss,predicted_range,predicted_first_day_gain_loss,sector,industry
0,0.791023,-0.431128,1.669573,-0.056427,0.195109,-0.404897,-3778000.0,-0.079211,1,0.999595,1,Industrials,Electrical Equipment & Parts
1,2.834215,-2.639492,1.821186,0.354131,0.999992,0.258264,-565045.0,0.326479,1,0.746272,1,Financial Services,Insurance-Diversified
2,0.000000,0.000000,0.000000,-2.237563,0.000000,-9.541401,-4358000.0,-4.306794,0,0.253892,0,Healthcare,Biotechnology
3,0.000000,0.000000,6.355345,0.000000,1.000027,-0.292881,4323000.0,-0.256404,0,0.655895,1,Other,Other
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.177614,0.0,0.000000,0,0.038971,0,Other,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.000000,0.000000,1.638391,-0.145572,0.658848,-0.349033,-2734000.0,-0.318951,0,0.837803,1,Other,Other
68,0.000000,0.000000,1.596467,0.362813,0.772729,0.128499,-58746000.0,0.140411,1,0.404624,0,Energy,Oil & Gas Equipment & Services
69,0.000000,0.000000,0.000000,0.572817,0.000000,0.000000,0.0,0.000000,1,0.000015,0,Other,Other
70,0.000000,0.000000,0.000000,1.122255,0.000000,-0.008407,0.0,0.000000,1,0.758314,1,Other,Other
71,0.000000,0.000000,0.000000,0.228440,0.000000,0.000000,0.0,0.000000,1,0.999856,1,Other,Other

In [22]:
new_first_day_df.to_csv('first_day_results_de-encoded.csv', index=False)

# 3 month return

In [23]:
three_month_df = pd.read_csv('../three_month_results.csv')
three_month_df

,Index,debt_asset_ratio,debt_equity_ratio,current_ratio,OCF_ratio,gross_profit_margin,net_profit_margin,cashflow_frominvestment,research_dev,ebitda,...,industry_Staffing & Employment Services,industry_Telecom Services,industry_Travel Services,industry_Utilities-Regulated Gas,industry_Utilities-Regulated Water,industry_Utilities-Renewable,industry_Waste Management,actual_gain_loss,predicted_range,predicted_gain_loss
0,516,0.791023,-0.431128,1.669573,-0.056427,0.195109,-0.404897,-3778000.0,14413000.0,0.0,...,0,0,0,0,0,0,0,1,0.998733,1
1,588,2.834215,-2.639492,1.821186,0.354131,0.999992,0.258264,-565045.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0.561512,1
2,841,0.000000,0.000000,0.000000,-2.237563,0.000000,-9.541401,-4358000.0,7079000.0,0.0,...,0,0,0,0,0,0,0,1,0.051525,0
3,1142,0.000000,0.000000,6.355345,0.000000,1.000027,-0.292881,4323000.0,4799000.0,0.0,...,0,0,0,0,0,0,0,1,0.587298,1
4,1777,0.000000,0.000000,0.000000,0.000000,0.000000,0.177614,0.0,294000.0,0.0,...,0,0,0,0,0,0,0,1,0.095285,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,1244,0.000000,0.000000,1.638391,-0.145572,0.658848,-0.349033,-2734000.0,3197000.0,0.0,...,0,0,0,0,0,0,0,1,0.582729,1
68,644,0.000000,0.000000,1.596467,0.362813,0.772729,0.128499,-58746000.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0.312227,0
69,1005,0.000000,0.000000,0.000000,0.572817,0.000000,0.000000,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0.767532,1
70,2200,0.000000,0.000000,0.000000,1.122255,0.000000,-0.008407,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0.339107,0
71,1430,0.000000,0.000000,0.000000,0.228440,0.000000,0.000000,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0.998464,1

In [24]:
undummied_three_df = undummify(three_month_df)

In [27]:
new_three_month_df = three_month_df[['debt_asset_ratio','debt_equity_ratio','current_ratio','OCF_ratio','gross_profit_margin','net_profit_margin','cashflow_frominvestment','cashflow_frominvestment','research_dev', 'ebitda','actual_gain_loss','predicted_range','predicted_gain_loss']]

In [28]:
new_three_month_df['sector'] = undummied_three_df['sector']
new_three_month_df

C:\Users\death\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,debt_asset_ratio,debt_equity_ratio,current_ratio,OCF_ratio,gross_profit_margin,net_profit_margin,cashflow_frominvestment,cashflow_frominvestment,research_dev,ebitda,actual_gain_loss,predicted_range,predicted_gain_loss,sector
0,0.791023,-0.431128,1.669573,-0.056427,0.195109,-0.404897,-3778000.0,-3778000.0,14413000.0,0.0,1,0.998733,1,Industrials
1,2.834215,-2.639492,1.821186,0.354131,0.999992,0.258264,-565045.0,-565045.0,0.0,0.0,1,0.561512,1,Financial Services
2,0.000000,0.000000,0.000000,-2.237563,0.000000,-9.541401,-4358000.0,-4358000.0,7079000.0,0.0,1,0.051525,0,Healthcare
3,0.000000,0.000000,6.355345,0.000000,1.000027,-0.292881,4323000.0,4323000.0,4799000.0,0.0,1,0.587298,1,Other
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.177614,0.0,0.0,294000.0,0.0,1,0.095285,0,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.000000,0.000000,1.638391,-0.145572,0.658848,-0.349033,-2734000.0,-2734000.0,3197000.0,0.0,1,0.582729,1,Other
68,0.000000,0.000000,1.596467,0.362813,0.772729,0.128499,-58746000.0,-58746000.0,0.0,0.0,0,0.312227,0,Energy
69,0.000000,0.000000,0.000000,0.572817,0.000000,0.000000,0.0,0.0,0.0,0.0,1,0.767532,1,Other
70,0.000000,0.000000,0.000000,1.122255,0.000000,-0.008407,0.0,0.0,0.0,0.0,0,0.339107,0,Other
71,0.000000,0.000000,0.000000,0.228440,0.000000,0.000000,0.0,0.0,0.0,0.0,1,0.998464,1,Other

In [29]:
new_three_month_df['industry'] = undummied_three_df['industry']
new_three_month_df

C:\Users\death\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,debt_asset_ratio,debt_equity_ratio,current_ratio,OCF_ratio,gross_profit_margin,net_profit_margin,cashflow_frominvestment,cashflow_frominvestment,research_dev,ebitda,actual_gain_loss,predicted_range,predicted_gain_loss,sector,industry
0,0.791023,-0.431128,1.669573,-0.056427,0.195109,-0.404897,-3778000.0,-3778000.0,14413000.0,0.0,1,0.998733,1,Industrials,Electrical Equipment & Parts
1,2.834215,-2.639492,1.821186,0.354131,0.999992,0.258264,-565045.0,-565045.0,0.0,0.0,1,0.561512,1,Financial Services,Insurance-Diversified
2,0.000000,0.000000,0.000000,-2.237563,0.000000,-9.541401,-4358000.0,-4358000.0,7079000.0,0.0,1,0.051525,0,Healthcare,Biotechnology
3,0.000000,0.000000,6.355345,0.000000,1.000027,-0.292881,4323000.0,4323000.0,4799000.0,0.0,1,0.587298,1,Other,Other
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.177614,0.0,0.0,294000.0,0.0,1,0.095285,0,Other,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.000000,0.000000,1.638391,-0.145572,0.658848,-0.349033,-2734000.0,-2734000.0,3197000.0,0.0,1,0.582729,1,Other,Other
68,0.000000,0.000000,1.596467,0.362813,0.772729,0.128499,-58746000.0,-58746000.0,0.0,0.0,0,0.312227,0,Energy,Oil & Gas Equipment & Services
69,0.000000,0.000000,0.000000,0.572817,0.000000,0.000000,0.0,0.0,0.0,0.0,1,0.767532,1,Other,Other
70,0.000000,0.000000,0.000000,1.122255,0.000000,-0.008407,0.0,0.0,0.0,0.0,0,0.339107,0,Other,Other
71,0.000000,0.000000,0.000000,0.228440,0.000000,0.000000,0.0,0.0,0.0,0.0,1,0.998464,1,Other,Other

In [30]:
new_three_month_df.to_csv('three_month_results_de-encoded.csv', index=False)